version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306

  phpmyadmin:
      depends_on:
          - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          MYSQL_ROOT_PASSWORD: root

# Names our volume
volumes:
    my-db: